[package]
name = "pomodoros"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = { version = "0.26", default-features = false, features = [
  "crossterm",
] }
crossterm = "0.27"
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
